name: "Semantic PRs"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure the types that are allowed in the PR title
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Configure if the PR title should be required to match the semantic format
          validateSingleCommit: false
          # Configure if the PR title should be validated even when other validations fail
          validateEvenWhenStatusExists: true